---
- name: "Customizing Parrot"
  hosts: localhost
  connection: local
  roles:
    - forensics-blue



    ADB
    AERoot
    Mobile Security Framework (MobSF)
    Frida
    Drozer
    Jalangi2
    KeyHacks
    NotKeyHacks
    apksigner
    jarsigner
    apktool
    zipalign
    Objection