- name: Install Bug Bounty Tools
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Debug role path
      debug:
        msg: "The role path should be: {{ playbook_dir }}/roles/firefox_extensions/firefox_extention_install"

    - name: Include firefox extensions Tools role
      include_role:
        name: firefox_extensions/firefox_extention_install
      tags:
        - extensions
