# roles/windows_tools/tasks/main.yml

- name: Install Windows tools
  win_chocolatey:
    name: "{{ item }}"
    state: present
  loop: "{{ windows_tools.pwnwin_tools + windows_tools.win_ref }}"
  when: ansible_os_family == 'Windows'
  environment:
    ChocolateyInstall: "{{ windows_tools_install_dir }}"

- name: Download additional packages
  win_get_url:
    url: "{{ item }}"
    dest: "{{ playbook_dir }}/downloads/{{ item | basename }}"
  loop: "{{ windows_tools.win_packages }}"
  when: ansible_os_family == 'Windows'

