---
- name: Create directory for CMS scanners
  file:
    path: /opt/bug_bounty/cms_scanner
    state: directory

- name: Change directory to CMS scanners
  shell: cd /opt/bug_bounty/cms_scanner

- name: Install Droopescan
  shell: pip3 install droopescan > /dev/null 2>&1
  args:
    chdir: /opt/bug_bounty/cms_scanner
  ignore_errors: yes

- name: Print Droopescan installation message
  debug:
    msg: "[CMS SCANNER] Droopescan installation is done!"

- name: Install AEM-Hacking
  shell: |
    git clone https://github.com/0ang3el/aem-hacker.git > /dev/null 2>&1
    cd aem-hacker
    pip3 install -r requirements.txt > /dev/null 2>&1
  args:
    chdir: /opt/bug_bounty/cms_scanner
  ignore_errors: yes

- name: Print AEM-Hacking installation message
  debug:
    msg: "[CMS SCANNER] AEM-Hacking installation is done!"
