---
- name: API Tools
  hosts: localhost
  become: yes
  vars:
    tools_directory: "/opt/bug_bounty/api_tools"
    kiterunner_version: "1.0.0"  # Update with the desired version
  tasks:
    - name: Create directory for API Tools
      file:
        path: "{{ tools_directory }}"
        state: directory

    - name: Install Kiterunner
      block:
        - name: Download Kiterunner binary
          get_url:
            url: "https://github.com/assetnote/kiterunner/releases/download/v{{ kiterunner_version }}/kiterunner_{{ kiterunner_version }}_linux_amd64.tar.gz"
            dest: "/tmp/kiterunner_{{ kiterunner_version }}_linux_amd64.tar.gz"

        - name: Extract Kiterunner
          unarchive:
            src: "/tmp/kiterunner_{{ kiterunner_version }}_linux_amd64.tar.gz"
            dest: "{{ tools_directory }}"
            remote_src: yes
            creates: "{{ tools_directory }}/kr"

        - name: Download Kiterunner wordlists
          get_url:
            url: "https://wordlists-cdn.assetnote.io/data/kiterunner/routes-large.kite.tar.gz"
            dest: "{{ tools_directory }}/kiterunner-wordlists/routes-large.kite.tar.gz"

        - name: Download Kiterunner wordlists
          get_url:
            url: "https://wordlists-cdn.assetnote.io/data/kiterunner/routes-small.kite.tar.gz"
            dest: "{{ tools_directory }}/kiterunner-wordlists/routes-small.kite.tar.gz"

        - name: Extract Kiterunner wordlists
          unarchive:
            src: "{{ item }}"
            dest: "{{ tools_directory }}/kiterunner-wordlists"
            remote_src: yes
            creates: "{{ item | basename | regex_replace('\\.tar\\.gz$','') }}"
          with_items:
            - "{{ tools_directory }}/kiterunner-wordlists/routes-large.kite.tar.gz"
            - "{{ tools_directory }}/kiterunner-wordlists/routes-small.kite.tar.gz"

      register: kiterunner_installed_block
      when: kiterunner_installed_block.changed

    - name: Print status
      debug:
        msg: "{{ item.msg }}"
      loop:
        - msg: "Kiterunner installed successfully!"
          when: kiterunner_installed_block.changed
