---
- name: Fuzzing Tools
  hosts: localhost
  become: yes
  vars:
    tools_directory: "/opt/bug_bounty/fuzzing_tools"
  tasks:
    - name: Create directory for Fuzzing Tools
      file:
        path: "{{ tools_directory }}"
        state: directory

    - name: Install ffuf
      shell: |
        go install github.com/ffuf/ffuf@latest
        ln -s ~/go/bin/ffuf /usr/local/bin/ffuf
      args:
        executable: /bin/bash
      register: ffuf_installed
      changed_when: ffuf_installed.rc == 0

    - name: Install Gobuster
      shell: |
        go install github.com/OJ/gobuster/v3@latest
        ln -s ~/go/bin/gobuster /usr/local/bin/gobuster
      args:
        executable: /bin/bash
      register: gobuster_installed
      changed_when: gobuster_installed.rc == 0

    - name: Install wfuzz
      apt:
        name: wfuzz
        state: present
      register: wfuzz_installed

    - name: Install fuzzuli
      shell: |
        go install github.com/musana/fuzzuli@latest
        ln -s ~/go/bin/fuzzuli /usr/local/bin/fuzzuli
      args:
        executable: /bin/bash
      register: fuzzuli_installed
      changed_when: fuzzuli_installed.rc == 0

    - name: Print status
      debug:
        msg: "{{ item.msg }}"
      loop:
        - msg: "ffuf installed successfully!"
          when: ffuf_installed.changed
        - msg: "Gobuster installed successfully!"
          when: gobuster_installed.changed
        - msg: "wfuzz installed successfully!"
          when: wfuzz_installed.changed
        - msg: "fuzzuli installed successfully!"
          when: fuzzuli_installed.changed
