---
- name: Web Crawling
  hosts: localhost
  become: yes
  vars:
    tools_directory: "/opt/bug_bounty/web_crawling"
  tasks:
    - name: Create directory for Web Crawling
      file:
        path: "{{ tools_directory }}"
        state: directory

    - name: Install Gospider
      shell: |
        go install github.com/jaeles-project/gospider@latest
        ln -s ~/go/bin/gospider /usr/local/bin/gospider
      args:
        executable: /bin/bash
      register: gospider_installed
      changed_when: gospider_installed.rc == 0

    - name: Install Hakrawler
      shell: |
        go install github.com/hakluke/hakrawler@latest
        ln -s ~/go/bin/hakrawler /usr/local/bin/hakrawler
      args:
        executable: /bin/bash
      register: hakrawler_installed
      changed_when: hakrawler_installed.rc == 0

    - name: Install Katana
      shell: |
        go install github.com/projectdiscovery/katana/cmd/katana@latest
        ln -s ~/go/bin/katana /usr/local/bin/katana
      args:
        executable: /bin/bash
      register: katana_installed
      changed_when: katana_installed.rc == 0

    - name: Print status
      debug:
        msg: "{{ item.msg }}"
      loop:
        - msg: "Gospider installed successfully!"
          when: gospider_installed.changed
        - msg: "Hakrawler installed successfully!"
          when: hakrawler_installed.changed
        - msg: "Katana installed successfully!"
          when: katana_installed.changed
